In [1]:
import pandas as pd
import os
import joblib

In [5]:
# events.csv

events = pd.read_csv(os.path.join("data", "events.csv"), index_col=0)
print(events.columns)

events.head()

Index(['user_id', 'session_id', 'timestamp', 'step', 'action_type',
       'reference', 'platform', 'city', 'device', 'current_filters',
       'impressions', 'prices', 'src', 'is_test', 'fake_impressions',
       'fake_prices', 'reversed_clickout_step', 'clickout_step',
       'clickout_max_step', 'dt', 'is_val'],
      dtype='object')

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,...,prices,src,is_test,fake_impressions,fake_prices,reversed_clickout_step,clickout_step,clickout_max_step,dt,is_val
0,RE84XPQB447X,90fdaae2c58dc,1541030423,1,search for poi,Disneyland Paris,US,"Marne-la-Vallée, France",desktop,Best Value,...,NaN,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,2,1,2,2018-11-01,0
1,WDPJ442S0Q1Z,cf0c96d88d2ef,1541030432,1,search for destination,"Birmingham, United Kingdom",UK,"Birmingham, United Kingdom",mobile,NaN,...,NaN,train,0,449896|147730|12522|152022|12544|12531|12516|2...,117|127|117|101|125|70|124|95|115|73|127|123|1...,3,1,3,2018-11-01,0
2,PCYB9NJCV2IS,47ba72122b04c,1541030442,1,search for destination,"Lisbon, Portugal",US,"Lisbon, Portugal",mobile,NaN,...,NaN,train,0,NaN,NaN,1,1,1,2018-11-01,0
3,RE84XPQB447X,90fdaae2c58dc,1541030454,2,interaction item rating,149255,US,"Marne-la-Vallée, France",desktop,NaN,...,NaN,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,4,1,4,2018-11-01,0
4,ORQ6U0KAMD2Q,73aaba45abc79,1541030468,1,interaction item rating,69865,US,"Red Lodge, USA",desktop,NaN,...,NaN,train,0,69511|69865|3867636|8258580|2217944|824256|893...,55|89|61|70|84|141|106|212|75|123|92,5,1,5,2018-11-01,0

In [6]:
del events

In [8]:
# item_dense_features

item_dense = pd.read_csv(os.path.join("data","item_dense_features.csv"), index_col=0)

print(item_dense.columns)

item_dense.head()

Index(['item_index', 'item_id', 'free_wifi_(combined)',
       'swimming_pool_(combined_filter)', 'car_park', 'serviced_apartment',
       'air_conditioning', 'spa_(wellness_facility)', 'pet_friendly',
       'all_inclusive_(upon_inquiry)', 'rating', 'stars', 'hotel_category'],
      dtype='object')

,item_index,item_id,free_wifi_(combined),swimming_pool_(combined_filter),car_park,serviced_apartment,air_conditioning,spa_(wellness_facility),pet_friendly,all_inclusive_(upon_inquiry),rating,stars,hotel_category
0,0,5101,0,0,1,0,1,0,0,0,2.0,4.0,hotel
1,1,5416,1,0,1,0,0,1,1,0,4.0,4.0,hotel
2,2,5834,1,0,1,0,0,0,0,0,3.0,3.0,hotel
3,3,5910,1,0,1,0,0,0,1,0,2.0,4.0,hotel
4,4,6066,1,1,1,0,0,1,1,0,2.0,4.0,hotel

In [9]:
del item_dense

In [13]:
# item_pois
item_pois = joblib.load(os.path.join("data", "item_pois.joblib"))

for i,j in list(sorted(item_pois.items()))[:10]:
    print(f"{i}: {j}")

5014: {'Freiburg Breisgau Central Station', 'Altstadt-Mitte'}
5015: {'Freiburg Breisgau Central Station', 'Altstadt-Mitte', 'Adler'}
5017: {'Freiburg Breisgau Central Station', 'Altstadt-Mitte'}
5020: {'Freiburg Breisgau Central Station', 'Altstadt-Mitte'}
5049: {'Old town of Heidelberg', 'Venice Simplon Orient Express', 'Brückentor'}
5050: {'Old town of Heidelberg', 'Venice Simplon Orient Express'}
5051: {'Brückentor'}
5052: {'Old town of Heidelberg', 'Venice Simplon Orient Express', 'Brückentor'}
5053: {'Old town of Heidelberg', 'Venice Simplon Orient Express'}
5054: {'Old town of Heidelberg', 'Venice Simplon Orient Express'}

In [112]:
# item_prices

item_prices = pd.read_csv(os.path.join("data","item_prices.csv"), index_col=0)

print(item_prices.columns)

item_prices.head(50)

Index(['price', 'ascending_price_rank', 'descending_price_rank',
       'ascending_price_rank_pct', 'min_price', 'max_price', 'price_count',
       'price_relative_to_min', 'price_range', 'price_range_div'],
      dtype='object')

,price,ascending_price_rank,descending_price_rank,ascending_price_rank_pct,min_price,max_price,price_count,price_relative_to_min,price_range,price_range_div
item_id,,,,,,,,,,
5001,82,1,4,0.250000,82,105,15,1.000000,23,1.280488
5001,84,2,3,0.500000,82,105,15,1.024390,23,1.280488
5001,94,3,2,0.750000,82,105,15,1.146341,23,1.280488
5001,105,4,1,1.000000,82,105,15,1.280488,23,1.280488
5002,72,1,4,0.250000,72,105,15,1.000000,33,1.458333
5002,75,2,3,0.500000,72,105,15,1.041667,33,1.458333
5002,91,3,2,0.750000,72,105,15,1.263889,33,1.458333
5002,105,4,1,1.000000,72,105,15,1.458333,33,1.458333
5003,106,1,4,0.250000,106,119,17,1.000000,13,1.122642
5003,109,2,3,0.500000,106,119,17,1.028302,13,1.122642
5003,112,3,2,0.750000,106,119,17,1.056604,13,1.122642
5003,119,4,1,1.000000,106,119,17,1.122642,13,1.122642
5004,128,1,4,0.250000,128,169,14,1.000000,41,1.320312
5004,139,2,3,0.500000,128,169,14,1.085938,41,1.320312
5004,163,3,2,0.750000,128,169,14,1.273438,41,1.320312
5004,169,4,1,1.000000,128,169,14,1.320312,41,1.320312
5005,160,1,1,1.000000,160,160,1,1.000000,0,1.000000
5006,220,1,1,1.000000,220,220,2,1.000000,0,1.000000
5009,220,1,1,1.000000,220,220,2,1.000000,0,1.000000
5011,104,1,2,0.500000,104,105,3,1.000000,1,1.009615
5011,105,2,1,1.000000,104,105,3,1.009615,1,1.009615
5013,135,1,1,1.000000,135,135,4,1.000000,0,1.000000
5014,74,1,11,0.090909,74,704,19,1.000000,630,9.513514
5014,86,2,10,0.181818,74,704,19,1.162162,630,9.513514
5014,108,3,9,0.272727,74,704,19,1.459459,630,9.513514
5014,114,4,8,0.363636,74,704,19,1.540541,630,9.513514
5014,117,5,7,0.454545,74,704,19,1.581081,630,9.513514
5014,122,6,6,0.545455,74,704,19,1.648649,630,9.513514
5014,129,7,5,0.636364,74,704,19,1.743243,630,9.513514
5014,136,8,4,0.727273,74,704,19,1.837838,630,9.513514
5014,138,9,3,0.818182,74,704,19,1.864865,630,9.513514
5014,144,10,2,0.909091,74,704,19,1.945946,630,9.513514
5014,704,11,1,1.000000,74,704,19,9.513514,630,9.513514
5015,73,1,12,0.083333,73,496,27,1.000000,423,6.794521
5015,79,2,11,0.166667,73,496,27,1.082192,423,6.794521
5015,80,3,10,0.250000,73,496,27,1.095890,423,6.794521
5015,87,4,9,0.333333,73,496,27,1.191781,423,6.794521
5015,88,5,8,0.416667,73,496,27,1.205479,423,6.794521
5015,93,6,7,0.500000,73,496,27,1.273973,423,6.794521
5015,97,7,6,0.583333,73,496,27,1.328767,423,6.794521
5015,105,8,5,0.666667,73,496,27,1.438356,423,6.794521
5015,106,9,4,0.750000,73,496,27,1.452055,423,6.794521
5015,152,10,3,0.833333,73,496,27,2.082192,423,6.794521
5015,181,11,2,0.916667,73,496,27,2.479452,423,6.794521
5015,496,12,1,1.000000,73,496,27,6.794521,423,6.794521
5016,116,1,3,0.333333,116,157,8,1.000000,41,1.353448
5016,150,2,2,0.666667,116,157,8,1.293103,41,1.353448
5016,157,3,1,1.000000,116,157,8,1.353448,41,1.353448
5017,61,1,11,0.090909,61,544,23,1.000000,483,8.918033
5017,76,2,10,0.181818,61,544,23,1.245902,483,8.918033

In [15]:
# item_sort_by_distance_stats
item_sort_by_dist = joblib.load(os.path.join("data", "item_sort_by_distance_stats.joblib"))

for i,j in list(sorted(item_sort_by_dist.items()))[:10]:
    print(f"{i}: {j}")

5049: 0.16666666666666666
5050: 0.3333333333333333
5051: 0.5
5052: 0.125
5054: 1.0
5055: 0.4583333333333333
5060: 0.9583333333333334
5061: 0.2916666666666667
5065: 0.75
5067: 1.0

In [16]:
# item_sort_by_rating_stats
item_sort_by_rating = joblib.load(os.path.join("data", "item_sort_by_rating_stats.joblib"))

for i,j in list(sorted(item_sort_by_rating.items()))[:10]:
    print(f"{i}: {j}")

5002: 0.20833333333333334
5003: 0.875
5004: 1.0
5014: 0.4166666666666667
5017: 0.9166666666666666
5049: 0.631578947368421
5051: 0.8421052631578947
5052: 0.3157894736842105
5116: 0.9583333333333334
5124: 0.9166666666666666

In [17]:
# item_sort_by_pop_stats
item_sort_by_pop_stats = joblib.load(os.path.join("data", "item_sort_by_popularity_stats.joblib"))

for i,j in list(sorted(item_sort_by_pop_stats.items()))[:10]:
    print(f"{i}: {j}")

5206: 0.9583333333333334
5209: 0.625
5219: 0.3333333333333333
5228: 0.5
5232: 0.041666666666666664
5233: 0.9166666666666666
5244: 0.2916666666666667
5249: 0.125
5250: 0.16666666666666666
5275: 0.375

In [20]:
# price_pct_by_city
price_pct_by_city = joblib.load(os.path.join("data", "price_pct_by_city.joblib"))

for i,j in list(sorted(price_pct_by_city.items()))[:10]:
    print(f"{i}: {j}")

("'s-Hertogenbosch, Netherlands", 67): 0.04
("'s-Hertogenbosch, Netherlands", 70): 0.08
("'s-Hertogenbosch, Netherlands", 73): 0.12
("'s-Hertogenbosch, Netherlands", 83): 0.16
("'s-Hertogenbosch, Netherlands", 84): 0.2
("'s-Hertogenbosch, Netherlands", 89): 0.24
("'s-Hertogenbosch, Netherlands", 91): 0.28
("'s-Hertogenbosch, Netherlands", 93): 0.32
("'s-Hertogenbosch, Netherlands", 94): 0.36
("'s-Hertogenbosch, Netherlands", 96): 0.4

In [25]:
##### price_pct_by_platform
price_pct_by_platform = joblib.load(os.path.join("data", "price_pct_by_platform.joblib"))

for i,j in list(sorted(price_pct_by_platform.items()))[:500]:
    print(f"{i}: {j}")

('AA', 5): 0.00016181229773462783
('AA', 6): 0.0008090614886731392
('AA', 7): 0.001941747572815534
('AA', 8): 0.0030744336569579287
('AA', 9): 0.004449838187702265
('AA', 10): 0.006472491909385114
('AA', 11): 0.008818770226537216
('AA', 12): 0.011245954692556634
('AA', 13): 0.01423948220064725
('AA', 14): 0.017475728155339806
('AA', 15): 0.021035598705501618
('AA', 16): 0.025485436893203883
('AA', 17): 0.031229773462783172
('AA', 18): 0.037297734627831716
('AA', 19): 0.04320388349514563
('AA', 20): 0.04927184466019417
('AA', 21): 0.055501618122977346
('AA', 22): 0.06262135922330098
('AA', 23): 0.06877022653721683
('AA', 24): 0.07402912621359223
('AA', 25): 0.08066343042071197
('AA', 26): 0.08826860841423949
('AA', 27): 0.09716828478964401
('AA', 28): 0.10493527508090615
('AA', 29): 0.11076051779935275
('AA', 30): 0.11877022653721683
('AA', 31): 0.12710355987055016
('AA', 32): 0.13624595469255663
('AA', 33): 0.14474110032362458
('AA', 34): 0.1512135922330097
('AA', 35): 0.1600323624595469
('AA', 36): 0.16877022653721682
('AA', 37): 0.1767799352750809
('AA', 38): 0.18519417475728156
('AA', 39): 0.19344660194174756
('AA', 40): 0.20242718446601943
('AA', 41): 0.20938511326860842
('AA', 42): 0.2168284789644013
('AA', 43): 0.2260517799352751
('AA', 44): 0.23503236245954692
('AA', 45): 0.2441747572815534
('AA', 46): 0.2511326860841424
('AA', 47): 0.25857605177993526
('AA', 48): 0.2676375404530744
('AA', 49): 0.2771844660194175
('AA', 50): 0.28762135922330095
('AA', 51): 0.2961165048543689
('AA', 52): 0.30323624595469256
('AA', 53): 0.3119741100323625
('AA', 54): 0.3215210355987055
('AA', 55): 0.3296925566343042
('AA', 56): 0.3372168284789644
('AA', 57): 0.3440938511326861
('AA', 58): 0.3509708737864078
('AA', 59): 0.35898058252427184
('AA', 60): 0.36666666666666664
('AA', 61): 0.3766990291262136
('AA', 62): 0.38681229773462783
('AA', 63): 0.3939320388349515
('AA', 64): 0.39983818770226537
('AA', 65): 0.4063915857605178
('AA', 66): 0.41432038834951457
('AA', 67): 0.42176375404530747
('AA', 68): 0.4299352750809062
('AA', 69): 0.43786407766990293
('AA', 70): 0.4459546925566343
('AA', 71): 0.4533980582524272
('AA', 72): 0.4608414239482201
('AA', 73): 0.46990291262135925
('AA', 74): 0.4796116504854369
('AA', 75): 0.488915857605178
('AA', 76): 0.49579288025889967
('AA', 77): 0.5019417475728155
('AA', 78): 0.5081715210355987
('AA', 79): 0.5142394822006473
('AA', 80): 0.5205501618122977
('AA', 81): 0.5279126213592233
('AA', 82): 0.5348705501618123
('AA', 83): 0.541504854368932
('AA', 84): 0.5470064724919094
('AA', 85): 0.5512135922330097
('AA', 86): 0.556957928802589
('AA', 87): 0.5634304207119741
('AA', 88): 0.5694174757281554
('AA', 89): 0.5758899676375404
('AA', 90): 0.5828478964401295
('AA', 91): 0.5881877022653722
('AA', 92): 0.5923139158576052
('AA', 93): 0.5969255663430421
('AA', 94): 0.6021844660194174
('AA', 95): 0.6076051779935275
('AA', 96): 0.612378640776699
('AA', 97): 0.6177993527508091
('AA', 98): 0.6242718446601941
('AA', 99): 0.6318770226537217
('AA', 100): 0.6392394822006473
('AA', 101): 0.6450647249190938
('AA', 102): 0.6498381877022654
('AA', 103): 0.6542880258899676
('AA', 104): 0.6584142394822007
('AA', 105): 0.6627022653721683
('AA', 106): 0.6677184466019418
('AA', 107): 0.6720064724919094
('AA', 108): 0.6760517799352751
('AA', 109): 0.6800970873786408
('AA', 110): 0.6850323624595469
('AA', 111): 0.6912621359223301
('AA', 112): 0.6966019417475728
('AA', 113): 0.7004854368932039
('AA', 114): 0.7044498381877022
('AA', 115): 0.7083333333333334
('AA', 116): 0.7118932038834952
('AA', 117): 0.7151294498381877
('AA', 118): 0.718042071197411
('AA', 119): 0.7216019417475729
('AA', 120): 0.7249190938511327
('AA', 121): 0.727831715210356
('AA', 122): 0.7308252427184466
('AA', 123): 0.7347087378640776
('AA', 124): 0.738915857605178
('AA', 125): 0.7424757281553398
('AA', 126): 0.746116504854369
('AA', 127): 0.7496763754045307
('AA', 128): 0.7533980582524272
('AA', 129): 0.7563915857605178
('AA', 130): 0.7588187702265372
('AA', 131): 0.7616504854368932
('AA', 132): 0.7639967637540453
('AA', 133): 0.7662621359223301
('AA', 134): 0.7689320388349514
('AA', 135): 0.7718446601941747
('AA', 136): 0.7749190938511327
('AA', 137): 0.7773462783171521
('AA', 138): 0.779368932038835
('AA', 139): 0.7817961165048544
('AA', 140): 0.7847087378640777
('AA', 141): 0.7885113268608415
('AA', 142): 0.7925566343042071
('AA', 143): 0.795631067961165
('AA', 144): 0.7980582524271844
('AA', 145): 0.8007281553398058
('AA', 146): 0.8031553398058252
('AA', 147): 0.8053398058252427
('AA', 148): 0.8084142394822007
('AA', 149): 0.8113268608414239
('AA', 150): 0.8135922330097087
('AA', 151): 0.8165857605177993
('AA', 152): 0.8197411003236246
('AA', 153): 0.8224110032362459
('AA', 154): 0.8244336569579288
('AA', 155): 0.8258090614886732
('AA', 156): 0.8267799352750809
('AA', 157): 0.8279935275080906
('AA', 158): 0.8301779935275081
('AA', 159): 0.8324433656957929
('AA', 160): 0.8344660194174758
('AA', 161): 0.8365695792880259
('AA', 162): 0.8382686084142394
('AA', 163): 0.8394822006472492
('AA', 164): 0.8410194174757282
('AA', 165): 0.8428802588996763
('AA', 166): 0.8450647249190939
('AA', 167): 0.8472491909385114
('AA', 168): 0.8487864077669903
('AA', 169): 0.85
('AA', 170): 0.8516990291262136
('AA', 171): 0.8538025889967638
('AA', 172): 0.855663430420712
('AA', 173): 0.8572815533980582
('AA', 174): 0.858495145631068
('AA', 175): 0.859546925566343
('AA', 176): 0.8605987055016181
('AA', 177): 0.8616504854368932
('AA', 178): 0.8627022653721683
('AA', 179): 0.8641585760517799
('AA', 180): 0.8657766990291262
('AA', 181): 0.8668284789644013
('AA', 182): 0.8679611650485437
('AA', 183): 0.8690938511326861
('AA', 184): 0.8703074433656958
('AA', 185): 0.872168284789644
('AA', 186): 0.874757281553398
('AA', 187): 0.8769417475728155
('AA', 188): 0.8785598705501618
('AA', 189): 0.8803398058252427
('AA', 190): 0.8819579288025889
('AA', 191): 0.8835760517799353
('AA', 192): 0.8851132686084142
('AA', 193): 0.8862459546925566
('AA', 194): 0.8872977346278317
('AA', 195): 0.8883495145631068
('AA', 196): 0.8890776699029126
('AA', 197): 0.8897249190938511
('AA', 198): 0.8906957928802589
('AA', 199): 0.8923948220064725
('AA', 200): 0.8940129449838188
('AA', 201): 0.8949838187702266
('AA', 202): 0.8961974110032362
('AA', 203): 0.8973300970873787
('AA', 204): 0.8983009708737864
('AA', 205): 0.8996763754045307
('AA', 206): 0.9007281553398059
('AA', 207): 0.9014563106796116
('AA', 208): 0.9023462783171521
('AA', 209): 0.9031553398058253
('AA', 210): 0.904126213592233
('AA', 211): 0.9052588996763754
('AA', 212): 0.9063106796116505
('AA', 213): 0.9073624595469255
('AA', 214): 0.9080097087378641
('AA', 215): 0.9084142394822007
('AA', 216): 0.9088187702265372
('AA', 217): 0.9095469255663431
('AA', 218): 0.9105987055016181
('AA', 219): 0.9114077669902912
('AA', 220): 0.9122977346278317
('AA', 221): 0.9136731391585761
('AA', 222): 0.9148058252427185
('AA', 223): 0.9158576051779935
('AA', 224): 0.916747572815534
('AA', 225): 0.9171521035598705
('AA', 226): 0.9179611650485436
('AA', 227): 0.9186893203883495
('AA', 228): 0.9190129449838188
('AA', 230): 0.919336569579288
('AA', 231): 0.9197411003236245
('AA', 232): 0.9202265372168285
('AA', 233): 0.9207928802588997
('AA', 234): 0.9216019417475728
('AA', 235): 0.9224110032362459
('AA', 236): 0.9233009708737864
('AA', 237): 0.9242718446601942
('AA', 238): 0.9248381877022653
('AA', 239): 0.9250809061488673
('AA', 240): 0.9256472491909385
('AA', 241): 0.9262135922330097
('AA', 242): 0.9263754045307443
('AA', 243): 0.9269417475728156
('AA', 244): 0.9279935275080906
('AA', 245): 0.9292071197411004
('AA', 246): 0.9301779935275081
('AA', 247): 0.9311488673139159
('AA', 248): 0.931957928802589
('AA', 249): 0.9325242718446602
('AA', 250): 0.9333333333333333
('AA', 251): 0.9338996763754045
('AA', 252): 0.934546925566343
('AA', 253): 0.9351941747572815
('AA', 254): 0.9355987055016182
('AA', 255): 0.936084142394822
('AA', 256): 0.9365695792880259
('AA', 257): 0.9371359223300971
('AA', 258): 0.9379449838187702
('AA', 259): 0.9385113268608414
('AA', 260): 0.938915857605178
('AA', 261): 0.9394012944983818
('AA', 262): 0.9398058252427185
('AA', 263): 0.9405339805825242
('AA', 264): 0.9412621359223301
('AA', 265): 0.941747572815534
('AA', 266): 0.9421521035598706
('AA', 267): 0.9424757281553398
('AA', 268): 0.9427993527508091
('AA', 269): 0.943042071197411
('AA', 270): 0.9434466019417476
('AA', 271): 0.9439320388349515
('AA', 272): 0.9442556634304207
('AA', 273): 0.9448220064724919
('AA', 274): 0.9455501618122978
('AA', 275): 0.9461165048543689
('AA', 276): 0.9465210355987055
('AA', 277): 0.9468446601941748
('AA', 278): 0.9470873786407767
('AA', 280): 0.9473300970873786
('AA', 281): 0.9475728155339805
('AA', 282): 0.9478155339805825
('AA', 283): 0.948220064724919
('AA', 284): 0.9485436893203884
('AA', 285): 0.9487864077669903
('AA', 286): 0.9490291262135923
('AA', 287): 0.9495145631067962
('AA', 288): 0.95
('AA', 289): 0.9503236245954693
('AA', 290): 0.9508899676375404
('AA', 291): 0.9515372168284789
('AA', 292): 0.9521844660194175
('AA', 293): 0.9525889967637541
('AA', 294): 0.9527508090614887
('AA', 295): 0.9529126213592233
('AA', 296): 0.9533980582524272
('AA', 297): 0.9539644012944983
('AA', 298): 0.9544498381877022
('AA', 299): 0.9549352750809061
('AA', 300): 0.9553398058252427
('AA', 301): 0.955663430420712
('AA', 302): 0.9558252427184466
('AA', 303): 0.9561488673139159
('AA', 304): 0.9566343042071197
('AA', 305): 0.957200647249191
('AA', 306): 0.9576051779935275
('AA', 307): 0.9580097087378641
('AA', 308): 0.9586569579288026
('AA', 309): 0.9591423948220065
('AA', 310): 0.9594660194174758
('AA', 311): 0.9597087378640776
('AA', 312): 0.9598705501618123
('AA', 313): 0.9601941747572815
('AA', 314): 0.9606796116504854
('AA', 315): 0.961084142394822
('AA', 319): 0.9614077669902913
('AA', 320): 0.9618932038834952
('AA', 321): 0.9624595469255663
('AA', 324): 0.9627831715210357
('AA', 326): 0.9630258899676375
('AA', 327): 0.9634304207119742
('AA', 328): 0.9638349514563107
('AA', 329): 0.9643203883495146
('AA', 332): 0.9647249190938512
('AA', 333): 0.9648867313915858
('AA', 336): 0.9650485436893204
('AA', 337): 0.9654530744336569
('AA', 338): 0.9658576051779936
('AA', 339): 0.9661003236245954
('AA', 340): 0.9664239482200647
('AA', 341): 0.9668284789644013
('AA', 342): 0.9672330097087378
('AA', 343): 0.9675566343042071
('AA', 344): 0.9678802588996763
('AA', 345): 0.9681229773462783
('AA', 346): 0.968284789644013
('AA', 347): 0.9685275080906149
('AA', 348): 0.9689320388349515
('AA', 349): 0.969336569579288
('AA', 350): 0.96957928802589
('AA', 351): 0.9697411003236246
('AA', 352): 0.9700647249190939
('AA', 357): 0.9704692556634305
('AA', 358): 0.9707119741100324
('AA', 359): 0.9710355987055016
('AA', 360): 0.9714401294498382
('AA', 362): 0.9716828478964401
('AA', 363): 0.9718446601941747
('AA', 364): 0.9720873786407767
('AA', 368): 0.9724919093851133
('AA', 369): 0.9731391585760518
('AA', 370): 0.9737864077669903
('AA', 374): 0.9741100323624595
('AA', 375): 0.9742718446601941
('AA', 377): 0.9744336569579288
('AA', 378): 0.9745954692556634
('AA', 380): 0.974757281553398
('AA', 381): 0.9749190938511327
('AA', 382): 0.9751618122977346
('AA', 383): 0.9754045307443365
('AA', 385): 0.9756472491909385
('AA', 386): 0.9758899676375404
('AA', 388): 0.976051779935275
('AA', 389): 0.9762135922330097
('AA', 394): 0.9764563106796117
('AA', 397): 0.9768608414239482
('AA', 399): 0.9771844660194174
('AA', 400): 0.9773462783171522
('AA', 404): 0.9775080906148867
('AA', 405): 0.9776699029126213
('AA', 407): 0.977831715210356
('AA', 408): 0.9779935275080907
('AA', 410): 0.9782362459546926
('AA', 411): 0.9784789644012944
('AA', 412): 0.9786407766990292
('AA', 413): 0.9789644012944984
('AA', 417): 0.9792880258899677
('AA', 418): 0.9794498381877023
('AA', 419): 0.9796116504854369
('AA', 420): 0.9799352750809062
('AA', 423): 0.9802588996763754
('AA', 432): 0.9805016181229773
('AA', 437): 0.9807443365695793
('AA', 439): 0.9809061488673139
('AA', 442): 0.9810679611650486
('AA', 444): 0.9812297734627832
('AA', 446): 0.9813915857605178
('AA', 447): 0.9815533980582525
('AA', 451): 0.9817152103559871
('AA', 452): 0.9818770226537217
('AA', 453): 0.9820388349514563
('AA', 454): 0.982200647249191
('AA', 463): 0.9823624595469256
('AA', 464): 0.9825242718446602
('AA', 467): 0.9826860841423948
('AA', 468): 0.9828478964401295
('AA', 470): 0.9830097087378641
('AA', 479): 0.9831715210355987
('AA', 497): 0.9834142394822006
('AA', 502): 0.9836569579288026
('AA', 503): 0.9838187702265372
('AA', 513): 0.9839805825242719
('AA', 514): 0.9841423948220065
('AA', 518): 0.9843042071197411
('AA', 522): 0.9844660194174757
('AA', 530): 0.9847087378640776
('AA', 534): 0.9849514563106796
('AA', 537): 0.9851132686084142
('AA', 544): 0.9852750809061489
('AA', 549): 0.9855177993527509
('AA', 553): 0.98584142394822
('AA', 555): 0.986084142394822
('AA', 562): 0.986326860841424
('AA', 564): 0.9865695792880259
('AA', 570): 0.9867313915857605
('AA', 578): 0.9868932038834951
('AA', 591): 0.9870550161812298
('AA', 600): 0.9872168284789644
('AA', 602): 0.987378640776699
('AA', 605): 0.9875404530744336
('AA', 610): 0.9877022653721683
('AA', 616): 0.9878640776699029
('AA', 622): 0.9880258899676375
('AA', 630): 0.9881877022653721
('AA', 633): 0.9884304207119741
('AA', 642): 0.988673139158576
('AA', 646): 0.9888349514563107
('AA', 652): 0.9889967637540453
('AA', 665): 0.9891585760517799
('AA', 666): 0.9893203883495145
('AA', 708): 0.9894822006472492
('AA', 709): 0.9896440129449838
('AA', 710): 0.9898058252427184
('AA', 746): 0.989967637540453
('AA', 783): 0.9901294498381877
('AA', 790): 0.9902912621359223
('AA', 794): 0.9904530744336569
('AA', 798): 0.9906148867313915
('AA', 808): 0.9907766990291262
('AA', 820): 0.9909385113268608
('AA', 829): 0.9911003236245954
('AA', 837): 0.9912621359223301
('AA', 851): 0.9914239482200647
('AA', 855): 0.9915857605177993
('AA', 869): 0.9917475728155339
('AA', 871): 0.9919093851132686
('AA', 876): 0.9920711974110032
('AA', 897): 0.9922330097087378
('AA', 900): 0.9923948220064724
('AA', 901): 0.9925566343042072
('AA', 905): 0.9927184466019418
('AA', 911): 0.9928802588996763
('AA', 932): 0.9930420711974111
('AA', 937): 0.9932038834951457
('AA', 939): 0.9933656957928803
('AA', 959): 0.9935275080906149
('AA', 963): 0.9936893203883496
('AA', 976): 0.9938511326860842
('AA', 1006): 0.9940129449838188
('AA', 1018): 0.9941747572815534
('AA', 1030): 0.9943365695792881
('AA', 1035): 0.9944983818770227
('AA', 1043): 0.9946601941747573
('AA', 1049): 0.9948220064724919
('AA', 1053): 0.9949838187702266
('AA', 1056): 0.9951456310679612
('AA', 1076): 0.9953074433656958
('AA', 1103): 0.9954692556634305
('AA', 1143): 0.9956310679611651
('AA', 1161): 0.9957928802588997
('AA', 1207): 0.9960355987055016
('AA', 1216): 0.9962783171521036
('AA', 1229): 0.9964401294498382
('AA', 1241): 0.9966019417475728
('AA', 1243): 0.9967637540453075
('AA', 1244): 0.9969255663430421
('AA', 1260): 0.9970873786407767
('AA', 1277): 0.9972491909385113
('AA', 1288): 0.997411003236246
('AA', 1414): 0.9975728155339806
('AA', 1490): 0.9977346278317152
('AA', 1499): 0.9978964401294499
('AA', 1546): 0.9980582524271845
('AA', 1561): 0.9982200647249191
('AA', 1585): 0.9983818770226537
('AA', 1655): 0.9985436893203884
('AA', 1713): 0.998705501618123
('AA', 2271): 0.9988673139158576
('AA', 2646): 0.9990291262135922
('AA', 3219): 0.9991909385113269
('AA', 3290): 0.9993527508090615
('AA', 4396): 0.9995145631067961
('AA', 4949): 0.9996763754045307
('AA', 6721): 0.9998381877022654
('AA', 8893): 1.0
('AE', 8): 0.000536097212294496
('AE', 9): 0.0012508934953538242
('AE', 10): 0.002144388849177984
('AE', 11): 0.0035739814152966403
('AE', 12): 0.004824874910650465
('AE', 13): 0.005718370264474625
('AE', 14): 0.006969263759828449
('AE', 15): 0.008756254467476769
('AE', 16): 0.01143674052894925
('AE', 17): 0.015368120085775554
('AE', 18): 0.01947819871336669

In [110]:
events = pd.read_csv("data/events.csv", index_col=0)

events["last_clickout_of_session"] = 0

events.loc[
    events[events["action_type"] == "clickout item"]
    .sort_values(["session_id", "step"], ascending=False)
    .drop_duplicates("session_id")
    .index,
    "last_clickout_of_session"
] = 1

events.to_csv("data/events.csv")

In [111]:
events = pd.read_csv("data/events.csv", index_col=0)

events.head(50)

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,...,src,is_test,fake_impressions,fake_prices,reversed_clickout_step,clickout_step,clickout_max_step,dt,is_val,last_clickout_of_session
0,RE84XPQB447X,90fdaae2c58dc,1541030423,1,search for poi,Disneyland Paris,US,"Marne-la-Vallée, France",desktop,Best Value,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,2,1,2,2018-11-01,0,0
1,WDPJ442S0Q1Z,cf0c96d88d2ef,1541030432,1,search for destination,"Birmingham, United Kingdom",UK,"Birmingham, United Kingdom",mobile,NaN,...,train,0,449896|147730|12522|152022|12544|12531|12516|2...,117|127|117|101|125|70|124|95|115|73|127|123|1...,3,1,3,2018-11-01,0,0
2,PCYB9NJCV2IS,47ba72122b04c,1541030442,1,search for destination,"Lisbon, Portugal",US,"Lisbon, Portugal",mobile,NaN,...,train,0,NaN,NaN,1,1,1,2018-11-01,0,0
3,RE84XPQB447X,90fdaae2c58dc,1541030454,2,interaction item rating,149255,US,"Marne-la-Vallée, France",desktop,NaN,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,4,1,4,2018-11-01,0,0
4,ORQ6U0KAMD2Q,73aaba45abc79,1541030468,1,interaction item rating,69865,US,"Red Lodge, USA",desktop,NaN,...,train,0,69511|69865|3867636|8258580|2217944|824256|893...,55|89|61|70|84|141|106|212|75|123|92,5,1,5,2018-11-01,0,0
5,7JNKFSPVOK5B,5536503217a1e,1541030471,1,search for destination,"Port Macquarie, Australia",AU,"Port Macquarie, Australia",desktop,NaN,...,train,0,952673|667591|3839570|1054268|1843249|2835401|...,121|153|96|126|194|238|106|116|114|207|113|120...,1,1,1,2018-11-01,0,0
6,ORQ6U0KAMD2Q,73aaba45abc79,1541030478,2,interaction item rating,69865,US,"Red Lodge, USA",desktop,NaN,...,train,0,69511|69865|3867636|8258580|2217944|824256|893...,55|89|61|70|84|141|106|212|75|123|92,4,2,5,2018-11-01,0,0
7,ORQ6U0KAMD2Q,73aaba45abc79,1541030478,3,interaction item rating,69865,US,"Red Lodge, USA",desktop,NaN,...,train,0,69511|69865|3867636|8258580|2217944|824256|893...,55|89|61|70|84|141|106|212|75|123|92,3,3,5,2018-11-01,0,0
8,ORQ6U0KAMD2Q,73aaba45abc79,1541030478,4,interaction item rating,69865,US,"Red Lodge, USA",desktop,NaN,...,train,0,69511|69865|3867636|8258580|2217944|824256|893...,55|89|61|70|84|141|106|212|75|123|92,2,4,5,2018-11-01,0,0
9,ORQ6U0KAMD2Q,73aaba45abc79,1541030484,5,clickout item,69865,US,"Red Lodge, USA",desktop,NaN,...,train,0,69511|69865|3867636|8258580|2217944|824256|893...,55|89|61|70|84|141|106|212|75|123|92,1,1,1,2018-11-01,0,1
10,ORQ6U0KAMD2Q,73aaba45abc79,1541030488,6,interaction item rating,69865,US,"Red Lodge, USA",desktop,NaN,...,train,0,NaN,NaN,1,5,5,2018-11-01,0,0
11,1BPL57EV423O,eb524efcd7bc9,1541030493,1,change of sort order,interaction sort button,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,4,1,4,2018-11-01,0,0
12,1BPL57EV423O,eb524efcd7bc9,1541030496,2,change of sort order,price and recommended,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,3,2,4,2018-11-01,0,0
13,1BPL57EV423O,eb524efcd7bc9,1541030496,3,filter selection,Best Value,ES,"Barcelona, Spain",mobile,Best Value,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,2,1,2,2018-11-01,0,0
14,6L00FD88A2OR,8ee1459e4849a,1541030496,1,search for destination,"Tralee, Ireland",IE,"Tralee, Ireland",desktop,NaN,...,train,0,4065852|39801|2342234|46042|46056|178062|23028...,70|75|112|85|65|103|70|64|99|42|79|120|125|120...,1,1,1,2018-11-01,0,0
15,1BPL57EV423O,eb524efcd7bc9,1541030502,4,change of sort order,interaction sort button,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,2,3,4,2018-11-01,0,0
16,1BPL57EV423O,eb524efcd7bc9,1541030505,5,change of sort order,price only,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,1,4,4,2018-11-01,0,0
17,1BPL57EV423O,eb524efcd7bc9,1541030505,6,filter selection,Sort by Price,ES,"Barcelona, Spain",mobile,Sort by Price,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,1,2,2,2018-11-01,0,0
18,RE84XPQB447X,90fdaae2c58dc,1541030507,3,interaction item image,1231946,US,"Marne-la-Vallée, France",desktop,NaN,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,85,1,85,2018-11-01,0,0
19,RE84XPQB447X,90fdaae2c58dc,1541030507,4,interaction item image,1231946,US,"Marne-la-Vallée, France",desktop,NaN,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,84,2,85,2018-11-01,0,0
20,RE84XPQB447X,90fdaae2c58dc,1541030518,5,interaction item image,1231946,US,"Marne-la-Vallée, France",desktop,NaN,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,83,3,85,2018-11-01,0,0
21,RE84XPQB447X,90fdaae2c58dc,1541030518,6,interaction item image,1231946,US,"Marne-la-Vallée, France",desktop,NaN,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,82,4,85,2018-11-01,0,0
22,RE84XPQB447X,90fdaae2c58dc,1541030518,7,interaction item image,1231946,US,"Marne-la-Vallée, France",desktop,NaN,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,81,5,85,2018-11-01,0,0
23,RE84XPQB447X,90fdaae2c58dc,1541030518,8,interaction item image,1231946,US,"Marne-la-Vallée, France",desktop,NaN,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,80,6,85,2018-11-01,0,0
24,RE84XPQB447X,90fdaae2c58dc,1541030518,9,interaction item image,1231946,US,"Marne-la-Vallée, France",desktop,NaN,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,79,7,85,2018-11-01,0,0
25,RE84XPQB447X,90fdaae2c58dc,1541030518,10,interaction item image,1231946,US,"Marne-la-Vallée, France",desktop,NaN,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,78,8,85,2018-11-01,0,0
26,RE84XPQB447X,90fdaae2c58dc,1541030518,11,interaction item image,1231946,US,"Marne-la-Vallée, France",desktop,NaN,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,77,9,85,2018-11-01,0,0
27,RE84XPQB447X,90fdaae2c58dc,1541030518,12,interaction item image,1231946,US,"Marne-la-Vallée, France",desktop,NaN,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,76,10,85,2018-11-01,0,0
28,RE84XPQB447X,90fdaae2c58dc,1541030518,13,interaction item image,1231946,US,"Marne-la-Vallée, France",desktop,NaN,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,75,11,85,2018-11-01,0,0
29,RE84XPQB447X,90fdaae2c58dc,1541030518,14,interaction item image,1231946,US,"Marne-la-Vallée, France",desktop,NaN,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,74,12,85,2018-11-01,0,0
30,RE84XPQB447X,90fdaae2c58dc,1541030518,15,interaction item image,1231946,US,"Marne-la-Vallée, France",desktop,NaN,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,73,13,85,2018-11-01,0,0
31,1BPL57EV423O,eb524efcd7bc9,1541030519,7,interaction item rating,40373,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,1,1,1,2018-11-01,0,0
32,RE84XPQB447X,90fdaae2c58dc,1541030519,16,clickout item,1231946,US,"Marne-la-Vallée, France",desktop,Best Value,...,train,0,8887828|8414618|1231946|7323680|5125642|415471...,98|119|105|98|145|120|156|145|180|125|168|138|...,1,1,1,2018-11-01,0,1
33,1BPL57EV423O,eb524efcd7bc9,1541030529,8,interaction item image,40373,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,19,1,19,2018-11-01,0,0
34,1BPL57EV423O,eb524efcd7bc9,1541030529,9,interaction item image,40373,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,18,2,19,2018-11-01,0,0
35,YENE1ELQ0UNP,309644ed98800,1541030530,1,clickout item,1054190,JP,"Tokorozawa, Japan",desktop,NaN,...,train,0,1054190|1522391|106189|106148|5910036|8770772|...,164|80|80|100|66|66|57|133|74|108|79|93|85|76|...,1,1,1,2018-11-01,0,1
36,02WCP0B2T48F,6c26e45791903,1541030539,1,clickout item,44932,US,"Montréal, Canada",mobile,NaN,...,train,0,44932|7107198|43946|5861070|88549|43822|144920...,47|109|138|109|91|106|134|43|171|101|70|134|87...,1,1,1,2018-11-01,0,1
37,1BPL57EV423O,eb524efcd7bc9,1541030539,10,interaction item image,40373,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,17,3,19,2018-11-01,0,0
38,1BPL57EV423O,eb524efcd7bc9,1541030539,11,interaction item image,40373,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,16,4,19,2018-11-01,0,0
39,1BPL57EV423O,eb524efcd7bc9,1541030549,12,interaction item image,40373,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,15,5,19,2018-11-01,0,0
40,1BPL57EV423O,eb524efcd7bc9,1541030549,13,interaction item image,40373,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,14,6,19,2018-11-01,0,0
41,1BPL57EV423O,eb524efcd7bc9,1541030549,14,interaction item image,40373,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,13,7,19,2018-11-01,0,0
42,1BPL57EV423O,eb524efcd7bc9,1541030549,15,interaction item image,40373,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,12,8,19,2018-11-01,0,0
43,1BPL57EV423O,eb524efcd7bc9,1541030549,16,interaction item image,40373,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,11,9,19,2018-11-01,0,0
44,1BPL57EV423O,eb524efcd7bc9,1541030549,17,interaction item image,40373,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,10,10,19,2018-11-01,0,0
45,1BPL57EV423O,eb524efcd7bc9,1541030549,18,interaction item image,40373,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,9,11,19,2018-11-01,0,0
46,1BPL57EV423O,eb524efcd7bc9,1541030549,19,interaction item image,40373,ES,"Barcelona, Spain",mobile,NaN,...,train,0,483816|4436860|40373|1063546|1275496|655601|67...,39|43|51|75|77|79|80|81|81|82|83|85|85|85|86|8...,8,12,19,2018-11-01,0,0
47,6L00FD88A2OR,8ee1459e4849a,1541030552,2,interaction item image,39801,IE,"Tralee, Ireland",desktop,NaN,...,train,0,4065852|39801|2342234|46042|46056|178062|23028...,70|75|112|85|65|103|70|64|99|42|79|120|125|120...,23,1,23,2018-11-01,0,0
48,6L00FD88A2OR,8ee1459e4849a,1541030552,3,interaction item image,39801,IE,"Tralee, Ireland",desktop,NaN,...,train,0,4065852|39801|2342234|46042|46056|178062|23028...,70|75|112|85|65|103|70|64|99|42|79|120|125|120...,22,2,23,2018-11-01,0,0
49,3XP6WLY1MS0C,f426a76b943a7,1541030554,1,search for destination,"Sharjah, United Arab Emirates",UK,"Sharjah, United Arab Emirates",desktop,NaN,...,train,0,1701253|1751043|8956|111409|4211794|1932423|36...,59|83|154|68|181|96|60|127|166|96|39|85|49|57|...,1,1,1,2018-11-01,0,0

In [105]:
events["last_clickout_of_session"] = 0
events.loc[events[events["action_type"] == "clickout item"].sort_values(["session_id", "step"], ascending=False).drop_duplicates("session_id").index, "last_clickout_of_session"] = 1